import {IDictionary} from '../types';

export default {
	'Type something': 'Start writing...',

	// About
	Advanced: 'Advanced',
	'About Jodit': 'About Jodit',
	'Jodit Editor': 'Jodit Editor',
	'Free Non-commercial Version': 'Free Non-commercial Version',
	"Jodit User's Guide": 'Jodit User\'s Guide',
	'contains detailed help for using': 'contains detailed help for using',
	'For information about the license, please go to our website:':
		'For information about the license, please go to our website:',
	'Buy full version': 'Buy full version',
	'Copyright © XDSoft.net - Chupurnov Valeriy. All rights reserved.':
		'Copyright © XDSoft.net - Chupurnov Valeriy.' + ' All rights reserved.',

	// Toolbar
	Anchor: 'Anchor',
	'Open in new tab': 'Open in new tab',
	'Open editor in fullsize': 'Open editor in fullsize',
	'Clear Formatting': 'Clear Formatting',
	'Fill color or set the text color': 'Fill color or set the text color',
	Redo: 'Redo',
	Undo: 'Undo',
	Bold: 'Bold',
	Italic: 'Italic',
	'Insert Unordered List': 'Insert Unordered List',
	'Insert Ordered List': 'Insert Ordered List',
	'Align Center': 'Align Center',
	'Align Justify': 'Align Justify',
	'Align Left': 'Align Left',
	'Align Right': 'Align Right',
	'Insert Horizontal Line': 'Insert Horizontal Line',
	'Insert image': 'Insert image',
	'Insert file': 'Insert file',
	'Insert youtube/vimeo video': 'Insert youtube/vimeo video',
	'Insert link': 'Insert link',
	'Font size': 'Font size',
	'Font family': 'Font family',

	'Insert format block': 'Insert format block',
	Normal: 'Normal',
	'Heading 1': 'Heading 1',
	'Heading 2': 'Heading 2',
	'Heading 3': 'Heading 3',
	'Heading 4': 'Heading 4',
	Quote: 'Quote',
	Code: 'Code',

	Insert: 'Insert',
	'Insert table': 'Insert table',

	'Decrease Indent': 'Decrease Indent',
	'Increase Indent': 'Increase Indent',
	'Select Special Character': 'Select Special Character',
	'Insert Special Character': 'Insert Special Character',

	'Paint format': 'Paint format',
	'Change mode': 'Change mode',

	// plugin Image
	Margins: 'Margins',
	top: 'top',
	right: 'right',
	bottom: 'bottom',
	left: 'left',
	Styles: 'Styles',
	Classes: 'Classes',
	Align: 'Align',
	Right: 'Right',
	Center: 'Center',
	Left: 'Left',
	'--Not Set--': '--Not Set--',
	Src: 'Src',
	Title: 'Title',
	Alternative: 'Alternative',
	Link: 'Link',
	'Open link in new tab': 'Open link in new tab',
	Image: 'Image',
	Advansed: 'Advansed',
	'Image properties': 'Image properties',
	Cancel: 'Cancel',
	Ok: 'Ok',

	// plugin paste
	'Your code is similar to HTML. Keep as HTML?':
		'Your code is similar to HTML. Keep as HTML?',
	'Paste as HTML': 'Paste as HTML',
	Keep: 'Keep',
	Clean: 'Clean',
	'Insert as Text': 'Insert as Text',
	'Word Paste Detected': 'Word Paste Detected',

	'The pasted content is coming from a Microsoft Word/Excel document. Do you want to keep the format or clean it up?':
		'The pasted content is coming from a Microsoft Word/Excel document. Do you want to keep the format or clean it up?',

	'Insert only Text': 'Insert only Text',

	// File Browser module
	'File Browser': 'File Browser',
	'Error on load list': 'Error on load list',
	'Error on load folders': 'Error on load folders',
	'Are you sure?': 'Are you sure?',
	'Enter Directory name': 'Enter Directory name',
	'Create directory': 'Create directory',
	'type name': 'type name',

	// Form module
	'Drop image': 'Drop image',
	'Drop file': 'Drop file',
	'or click': 'or click',
	'Alternative text': 'Alternative text',
	Browse: 'Browse',
	Upload: 'Upload',
	Background: 'Background',
	Text: 'Text',

	// popap module
	Top: 'Top',
	Middle: 'Middle',
	Bottom: 'Bottom',
	'Insert column before': 'Insert column before',
	'Insert column after': 'Insert column after',
	'Insert row above': 'Insert row above',
	'Insert row below': 'Insert row below',
	'Delete table': 'Delete table',
	'Delete row': 'Delete row',
	'Delete column': 'Delete column',
	'Empty cell': 'Empty cell',

	Delete: 'Delete',
	'Strike through': 'Strike through',
	Underline: 'Underline',
	Break: 'Pause',
	'Search for': 'Search for',
	'Replace with': 'Replace with',
	Replace: 'Replace',
	Edit: 'Edit',
	'Vertical align': 'Vertical align',
	'Horizontal align': 'Horizontal align',
	Filter: 'Filter',
	'Sort by changed': 'Sort by changed',
	'Sort by name': 'Sort by name',
	'Sort by size': 'Sort by size',
	'Add folder': 'Add folder',
	Split: 'Split',
	'Split vertical': 'Split vertical',
	'Split horizontal': 'Split horizontal',
	Merge: 'Merge',
	'Add column': 'Add column',
	'Add row': 'Add row',
	Border: 'Border',
	'Embed code': 'Embed code',
	Update: 'Update',
	superscript: 'superscript',
	subscript: 'subscript',
	'Cut selection': 'Cut selection',
	Paste: 'Paste',
	'Choose Content to Paste': 'Choose Content to Paste',

	// stat
	'Chars: %d': 'Chars: %d',
	'Words: %d': 'Words: %d',

	All: 'All',
	'Select %s': 'Select %s',
	'Select all': 'Select all',

	source: 'source',
	bold: 'bold',
	italic: 'italic',
	brush: 'brush',
	link: 'link',
	undo: 'undo',
	redo: 'redo',
	table: 'table',
	image: 'image',
	file: 'file',
	eraser: 'eraser',
	paragraph: 'paragraph',
	fontsize: 'fontsize',
	video: 'video',
	font: 'font',
	about: 'about',
	print: 'print',
	symbol: 'symbol',
	underline: 'underline',
	strikethrough: 'strikethrough',
	indent: 'indent',
	outdent: 'outdent',
	fullsize: 'fullsize',
	shrink: 'shrink',
	copyformat: 'copyformat',
	hr: 'hr',
	ul: 'ul',
	ol: 'ol',
	cut: 'cut',
	selectall: 'selectall',
	'Open link': 'Open link',
	'Edit link': 'Edit link',
	'No follow': 'No follow',
	Unlink: 'Unlink',
	Eye: 'Eye',
	pencil: 'Edit',
	' URL': 'URL',
	Reset: 'Reset',
	Save: 'Save',
	'Save as ...': 'Save as ...',
	Resize: 'Resize',
	Crop: 'Crop',
	Width: 'Width',
	Height: 'Height',
	'Keep Aspect Ratio': 'Keep Aspect Ratio',
	Yes: 'Yes',
	No: 'No',
	Remove: 'Remove',
	Select: 'Select',
	'You can only edit your own images. Download this image on the host?':
		'You can only edit your own images. ' +
		'Download this image on the host?',
	'The image has been successfully uploaded to the host!': 'The image has been successfully uploaded to the host!',
	palette: 'palette',
	'There are no files': 'There are no files',
	Rename: 'Rename',
	'Enter new name': 'Enter new name',
	preview: 'preview',
	download: 'download',
	'Paste from clipboard': 'Paste from clipboard',
	'Your browser doesn\'t support direct access to the clipboard.': 'Your browser doesn\\\'t support direct access to the clipboard.',
	'Copy selection': 'Copy selection',
	copy: 'copy',
	'Border radius': 'Border radius',
	'Show all': 'Show all',
	'Upload %s to cloud.': 'Upload %s to cloud.',
	'( The Max. file size is %s. )': '( The Max. file size is %s. )',
} as IDictionary<string>;
